// src/components/Navbar.svelte
<script>
	import { MoonFill, SunFill } from "svelte-bootstrap-icons";

	export let lightMode = false;
</script>

<header>
	<div><b>Sabyasachi Bhoi</b></div>
	<div>
		<button on:click>
			{#if lightMode}
				<MoonFill />
			{:else}
				<SunFill />
			{/if}
		</button>
	</div>
</header>

<style>
	header {
		margin-block: 1rem;
		padding-inline: 0.5rem;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
	}

	button {
		color: inherit;
		background: none;
		padding: 0.8rem;
		border: none;
		border-radius: 0.5rem;
	}
	button:hover {
		background-color: orange;
	}
</style>

// components/NavBar.jsx
import { BsFillMoonFill, BsSunFill } from 'react-icons/bs';

const NavBar = ({ theme, setTheme }) => {

	const handleThemeSwitch = () => {
		setTheme(theme === 'dark' ? 'light' : 'dark');
	}

  return (
    <div className='flex flex-row justify-between py-4 items-center'>
      <div className='font-bold text-lg'>Sabyasachi Bhoi</div>
      <button
        className='p-3 outline-none hover:outline-gray-400 rounded-lg'
        onClick={handleThemeSwitch}
      >
        {theme === 'light' ? <BsFillMoonFill /> : <BsSunFill/>}
      </button>
    </div>
  );
};

export default NavBar;
