// src/components/Navbar.svelte
<script>
	import { MoonFill, SunFill } from "svelte-bootstrap-icons";

	export let lightMode = false;
</script>

<header>
	<div><b>Sabyasachi Bhoi</b></div>
	<div>
		<button on:click>
			{#if lightMode}
				<MoonFill />
			{:else}
				<SunFill />
			{/if}
		</button>
	</div>
</header>

<style>
	header {
		margin-block: 1rem;
		padding-inline: 0.5rem;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
	}

	button {
		color: inherit;
		background: none;
		padding: 0.8rem;
		border: none;
		border-radius: 0.5rem;
	}
	button:hover {
		background-color: orange;
	}
</style>

// src/components/Navbar.tsx
import { BsMoonFill, BsSunFill } from 'solid-icons/bs';
import { useTheme } from '../ThemeProvider';

const Navbar = () => {
	const [dark, setDark] = useTheme();

  let headerStyle = {
    "padding": "1rem",
    "padding-inline": "0.5rem",
    "display": "flex",
    "flex-direction": "row",
    "justify-content": "space-between",
    "align-items": "center",
  };

  return (
    <header style={headerStyle}>
      <b>Sabyasachi Bhoi</b>
      <button onclick={() => setDark(!dark())}>{dark() ? <BsSunFill/> : <BsMoonFill/>}</button>
    </header>
  );
};

export default Navbar;
