// components/Work.jsx
import Section from './Section';

const Work = () => {
  return (
    <Section title='Work'>
      I&apos;m a second-year engineering student at Birla Institute of
      Technology and Science. I&apos;m a Linux enthusiast. I use GNU/Linux as my
      primary driver, and like to tinker around with new, free and open-source
      projects.
    </Section>
  );
};

export default Work;

// src/components/Work.svelte
<script>
	import InfoSection from "./InfoSection.svelte";
</script>

<InfoSection title="Work">
	I'm a second-year engineering student at Birla Institute of Technology and
	Science. I'm a Linux enthusiast. I use GNU/Linux as my primary driver, and
	like to tinker around with new, free and open-source projects.
</InfoSection>
